### ISSUE TITLE
code block style

### ISSUE THREAD

**Issue by wong2** [NdYAG/ANNO#33]
![qq20140626-1](https://cloud.githubusercontent.com/assets/321947/3396478/65a9a9dc-fd0f-11e3-9a30-0fd92ace1a99.png)

已知吗？

**Comment by NdYAG** [comment]
@wong2  怎么写的？
用这个语法吧

``````
\```erlang
def fooo(x):
    x += 1
    return x
\```
``````

https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by wong2** [comment]
哦好的，我直接四个空格缩进的方法。。
