### ISSUE TITLE
编辑框中存在代码项

### ISSUE THREAD

**Issue by TheKiteRunning** [NdYAG/ANNO#36]
您好，偶然发现您的这个作品，非常喜欢，使用时遇到一点问题，烦请方便时看一下。

![image](https://user-images.githubusercontent.com/24802332/30911730-50c91c08-a3bc-11e7-9f5e-2472209d8e32.png)

感谢!

**Comment by NdYAG** [comment]
@TheKiteRunning 你好，Chrome Store 中已更新到 0.2.9. 下载新版后支持编辑豆瓣新编辑器生成的日记。但在 Web 上使用新编辑可能无法打开旧编辑器产生的日记，目前已咨询豆瓣相关开发者，正在处理中。

**Comment by TheKiteRunning** [comment]
github用得少，才看到。非常喜欢这个作品，更感谢您的快速响应，祝您的豆瓣笔记和豆瓣一起越来越好。
